// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Ii8pR9MoFnRpZ--S26OyiypsR87USN8',
    appId: '1:933475773656:web:51a416db7d464b720c3bad',
    messagingSenderId: '933475773656',
    projectId: 'uifirebase-b91d2',
    authDomain: 'uifirebase-b91d2.firebaseapp.com',
    storageBucket: 'uifirebase-b91d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ZkhTtPUdMwy0SXLWxQN-zZwTwNMDum4',
    appId: '1:933475773656:android:f645fc197817510f0c3bad',
    messagingSenderId: '933475773656',
    projectId: 'uifirebase-b91d2',
    storageBucket: 'uifirebase-b91d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6NktXf30vb3kAXGazxHmXQwTy0GzOks',
    appId: '1:933475773656:ios:e5f180de74c4c8be0c3bad',
    messagingSenderId: '933475773656',
    projectId: 'uifirebase-b91d2',
    storageBucket: 'uifirebase-b91d2.firebasestorage.app',
    iosBundleId: 'com.example.propertyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6NktXf30vb3kAXGazxHmXQwTy0GzOks',
    appId: '1:933475773656:ios:e5f180de74c4c8be0c3bad',
    messagingSenderId: '933475773656',
    projectId: 'uifirebase-b91d2',
    storageBucket: 'uifirebase-b91d2.firebasestorage.app',
    iosBundleId: 'com.example.propertyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Ii8pR9MoFnRpZ--S26OyiypsR87USN8',
    appId: '1:933475773656:web:fce5d3816676cf020c3bad',
    messagingSenderId: '933475773656',
    projectId: 'uifirebase-b91d2',
    authDomain: 'uifirebase-b91d2.firebaseapp.com',
    storageBucket: 'uifirebase-b91d2.firebasestorage.app',
  );
}
